browser:
    pattern: /
    defaults: { _controller: DarkTranslationBundle:Browser:listDir }

docs:
    pattern: /docs/
    defaults: { _controller: DarkTranslationBundle:Docs:show }

list:
    pattern: /{path}/list.html
    defaults: { _controller: DarkTranslationBundle:Browser:listDir }
    requirements:
        path: ".+"

mkdir:
    pattern: /{path}/mkdir.html
    defaults: { _controller: DarkTranslationBundle:Browser:mkdir }
    requirements:
        path: ".+"

edit:
    pattern: /{path}/edit.html
    defaults: { _controller: DarkTranslationBundle:Browser:edit }
    requirements:
        path: ".+"

save:
    pattern: /{path}/save.html
    defaults: { _controller: DarkTranslationBundle:Browser:save }
    requirements:
        path: ".+"

show:
    pattern: /docs/{path}
    defaults: { _controller: DarkTranslationBundle:Docs:show }
    requirements:
        path: ".+"