parameters:
    dark_translation.browser.class: Dark\TranslationBundle\Browser\Browser
    dark_translation.extension.class: Dark\TranslationBundle\Twig\DocsExtension

services:
     dark_translation.browser:
        class: %dark_translation.browser.class%
        arguments:
            - [%dark_translation.source.base_dir%, %dark_translation.source.from%, %dark_translation.source.to%, %dark_translation.build.path%]

     dark_translation.twig.docs_extension:
        class: %dark_translation.extension.class%
        arguments:
            - %dark_translation.build.path%
        tags:
            - { name: twig.extension }